###### To solve a puzzle, you are given an initial state and a goal state.
###### Target is to reach goal state from initial state using puzzle rules.
######  We can move blank tile only on left, right, up, and down
![Capture.JPG](attachment:Capture.JPG)

# Generate an intial state of NPuzzle

In [ ]:
import numpy as np
import random
def get_state(N):    
    state = [item for item in range(N*N)]# [0,1,2,...,15]
    #print(state)
    random.shuffle(state)
    #print(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [ ]:
get_state(3)

[[7 3 0]
 [2 8 5]
 [4 1 6]]


[7, 3, 0, 2, 8, 5, 4, 1, 6]

# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



![Capture.JPG](attachment:Capture.JPG)

In [ ]:
def count_inversion(state):
    #arr = [i for i in arr if i !=0]
    print(state)
    inversion = []
    for i in range(len(state)):    
        count = 0
        for j in range(i+1,len(state)):        
            if state[i] > state[j]: 
                count = count + 1
        inversion.append(count)
    #print(inversion)
    return sum(inversion)

In [ ]:
s = get_state(4)
count_inversion(s)

[[ 2 33 17 15 27 21]
 [ 7 12  6 18 16 19]
 [28 31 14 20  3  8]
 [30 25 32 10  9  1]
 [ 5 26 34 29 13 23]
 [ 4 24 11 35 22  0]]
[2, 33, 17, 15, 27, 21, 7, 12, 6, 18, 16, 19, 28, 31, 14, 20, 3, 8, 30, 25, 32, 10, 9, 1, 5, 26, 34, 29, 13, 23, 4, 24, 11, 35, 22, 0]


310

# **Find blank row**

In [ ]:
# find row position of the blank tile
import math
def get_blank_row(state):
  l= len(state)
  pos=state.index(0)
  n=int(math.sqrt(l))
  return n - pos//n


In [ ]:
 get_blank_row(s)

1

# Solvability Rules

In [ ]:
def even(num):
  if (num % 2) == 0 :
    return True
  return False

In [ ]:
# apply the rules to decide solvability
#  N, I, R
# define a method to return solvability (input S)
# return True if solvable or False if not

def isSolvable(initialState):
  N = int(math.sqrt(len(initialState)))
  I = count_inversion(initialState)
  R = get_blank_row(initialState)

  if(even(N) and not even(R) and even(I)): return True
  elif(even(N) and even(R) and not even(I)): return True
  elif(not even(N) and even(I)): return True

  return False
  

  

  


In [ ]:
while(True):
  S = get_state(4)
  if isSolvable(S) : break


[[15  4 13  0]
 [14  6  1  7]
 [ 3  9  2 10]
 [ 5 11 12  8]]
[15, 4, 13, 0, 14, 6, 1, 7, 3, 9, 2, 10, 5, 11, 12, 8]
